In [1]:
import pandas as pd

In [2]:
# Specify the file path
file_path = 'data/Tab_delimited_text/Hackathon2024.ATAC.txt'
atac = pd.read_csv(file_path, sep='\t')
atac.head()

,peak,AAACCAACACAATGCC.1,AAACCAACAGGAACTG.1,AAACCAACATAATCCG.1,AAACCAACATTGTGCA.1,AAACCGCGTACTTCAC.1,AAACCGGCATAATCAC.1,AAACGCGCAGCAAGAT.1,AAACGGATCCCATAGG.1,AAAGCAAGTGCTAGCG.1,...,TTTGTCCCAGTAGGAT.1,TTTGTCTAGCTATTAG.1,TTTGTCTAGGACCTGC.1,TTTGTGAAGCGATACT.1,TTTGTGAAGGAACGGT.1,TTTGTGGCAGCAACCT.1,TTTGTGTTCATTGACA.1,TTTGTGTTCGTCAAGT.1,TTTGTGTTCTCCATAT.1,TTTGTTGGTCAGGAAG.1
0,chr1-10109-10357,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,chr1-180730-181630,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
2,chr1-191491-191736,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,chr1-267816-268196,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,chr1-586028-586373,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
# Create a mapping for chromosomes
mapping = {f'chr{i}': f'{i}' for i in range(1, 23)}
mapping.update({'chrX': 'X', 'chrY': 'Y'})
atac[['chromosome', 'peak_start_pos', 'peak_end_pos']] = atac['peak'].str.split('[-]', expand=True)

# Replace values in the DataFrame
atac['chromosome'] = atac['chromosome'].map(mapping)

atac.head(10)

,peak,AAACCAACACAATGCC.1,AAACCAACAGGAACTG.1,AAACCAACATAATCCG.1,AAACCAACATTGTGCA.1,AAACCGCGTACTTCAC.1,AAACCGGCATAATCAC.1,AAACGCGCAGCAAGAT.1,AAACGGATCCCATAGG.1,AAAGCAAGTGCTAGCG.1,...,TTTGTGAAGGAACGGT.1,TTTGTGGCAGCAACCT.1,TTTGTGTTCATTGACA.1,TTTGTGTTCGTCAAGT.1,TTTGTGTTCTCCATAT.1,TTTGTTGGTCAGGAAG.1,chromosome,peak_start_pos,peak_end_pos,chromosome_type
0,chr1-10109-10357,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,10109,10357,Unknown
1,chr1-180730-181630,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,1,180730,181630,Unknown
2,chr1-191491-191736,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,191491,191736,Unknown
3,chr1-267816-268196,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,267816,268196,Unknown
4,chr1-586028-586373,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,586028,586373,Unknown
5,chr1-629721-630172,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,629721,630172,Unknown
6,chr1-633793-634264,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,1,633793,634264,Unknown
7,chr1-777634-779926,2,0,2,0,6,0,2,0,0,...,0,2,0,0,0,0,1,777634,779926,Unknown
8,chr1-816881-817647,0,0,0,2,2,2,2,0,0,...,0,0,0,0,0,2,1,816881,817647,Unknown
9,chr1-819912-823500,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,1,819912,823500,Unknown

In [14]:
# Define the chromosome to type mapping
def map_chromosome_type(chromosome):
    metacentric = ['1', '3', '16', '19', '20']
    submetacentric = ['2', '4', '5', '6', '7', '8', '9', '10', '11', '12', '17', '18', 'X']
    acrocentric = ['13', '14', '15', '21', '22', 'Y']
    
    if chromosome in metacentric:
        return 'Metacentric'
    elif chromosome in submetacentric:
        return 'Submetacentric'
    elif chromosome in acrocentric:
        return 'Acrocentric'
    else:
        return 'Unknown'

# Apply the mapping to the atac['chromosome'] column
atac['chromosome_type'] = atac['chromosome'].apply(map_chromosome_type)
atac.head()

,peak,AAACCAACACAATGCC.1,AAACCAACAGGAACTG.1,AAACCAACATAATCCG.1,AAACCAACATTGTGCA.1,AAACCGCGTACTTCAC.1,AAACCGGCATAATCAC.1,AAACGCGCAGCAAGAT.1,AAACGGATCCCATAGG.1,AAAGCAAGTGCTAGCG.1,...,TTTGTGAAGGAACGGT.1,TTTGTGGCAGCAACCT.1,TTTGTGTTCATTGACA.1,TTTGTGTTCGTCAAGT.1,TTTGTGTTCTCCATAT.1,TTTGTTGGTCAGGAAG.1,chromosome,peak_start_pos,peak_end_pos,chromosome_type
0,chr1-10109-10357,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,10109,10357,Metacentric
1,chr1-180730-181630,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,1,180730,181630,Metacentric
2,chr1-191491-191736,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,191491,191736,Metacentric
3,chr1-267816-268196,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,267816,268196,Metacentric
4,chr1-586028-586373,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,586028,586373,Metacentric

In [16]:
atac['chromosome_type'].unique()

array(['Metacentric', 'Submetacentric', 'Acrocentric'], dtype=object)

In [17]:
# Specify the file path
file_path = 'data/Tab_delimited_text/Hackathon2024.RNA.txt'
rna = pd.read_csv(file_path, sep='\t')
rna.head()

,gene,AAACCAACACAATGCC.1,AAACCAACAGGAACTG.1,AAACCAACATAATCCG.1,AAACCAACATTGTGCA.1,AAACCGCGTACTTCAC.1,AAACCGGCATAATCAC.1,AAACGCGCAGCAAGAT.1,AAACGGATCCCATAGG.1,AAAGCAAGTGCTAGCG.1,...,TTTGTCCCAGTAGGAT.1,TTTGTCTAGCTATTAG.1,TTTGTCTAGGACCTGC.1,TTTGTGAAGCGATACT.1,TTTGTGAAGGAACGGT.1,TTTGTGGCAGCAACCT.1,TTTGTGTTCATTGACA.1,TTTGTGTTCGTCAAGT.1,TTTGTGTTCTCCATAT.1,TTTGTTGGTCAGGAAG.1
0,MIR1302-2HG,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,FAM138A,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,OR4F5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AL627309.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AL627309.3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
rna['gene']

0        MIR1302-2HG
1            FAM138A
2              OR4F5
3         AL627309.1
4         AL627309.3
            ...
36596     AC141272.1
36597     AC023491.2
36598     AC007325.1
36599     AC007325.4
36600     AC007325.2
Name: gene, Length: 36601, dtype: object

In [ ]:
# Define the prefix to gene type mapping
def map_gene_type(gene):
    protein_coding_prefixes = []  # No specific prefixes for protein-coding genes
    lncRNA_prefixes = ['LINC', 'MIR', 'AL', 'AC']
    small_rna_prefixes = ['SNORD', 'SNORA', 'RNU', 'MIR']
    pseudogene_prefixes = ['AC', 'AL', 'RP', 'AP']

    if any(gene.startswith(prefix) for prefix in lncRNA_prefixes):
        return 'Long non-coding RNA'
    elif any(gene.startswith(prefix) for prefix in small_rna_prefixes):
        return 'Small non-coding RNA'
    elif any(gene.startswith(prefix) for prefix in pseudogene_prefixes):
        return 'Pseudogene'
    else:
        return 'Protein-coding'

# Apply the mapping to the atac['gene'] column
atac['gene_type'] = atac['gene'].apply(map_gene_type)